{{- if and (not .Values.secret.existingSecretName) .Values.secret.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zocr-suite.fullname" . }}-secret
type: Opaque
stringData:
  {{ .Values.secret.keyName }}: {{ .Values.secret.apiKey | quote }}
{{- end }}

